routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\ProductsController;
use App\Http\Controllers\Admin\RolesController;
use App\Http\Controllers\Admin\RegionsController;
use App\Http\Controllers\Admin\PagesController;
use App\Http\Controllers\Admin\CatsController;
use App\Http\Controllers\Admin\PropsController;
use App\Http\Controllers\Admin\PropvalsController;
use App\Http\Controllers\Admin\TproductsController;
use App\Http\Controllers\Admin\ImportlogsController;
use App\Http\Controllers\Admin\ImgsController;
use App\Http\Controllers\Admin\TimgsController;
use App\Http\Controllers\Admin\TpropsController;
use App\Http\Controllers\Admin\OrdersController;
use App\Http\Controllers\Admin\MailingsController;
use App\Http\Controllers\Admin\MailusersController;
use App\Http\Controllers\Admin\SettingsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('layouts.app');
});*/

Route::get('/', 'App\Http\Controllers\PagesController@index');

Route::get('/products', 'App\Http\Controllers\ProductsController@index')->name('products');
Route::get('/products/{id}', 'App\Http\Controllers\ProductsController@show')->where('id', '[0-9]+')->name('products.show');
Route::get('/pages/{url}', 'App\Http\Controllers\PagesController@view')->where('url', '[A-Za-z0-9]+');
Route::get('/mailusers/index', 'App\Http\Controllers\MailusersController@index');
Route::get('/users/activate/{id}/{code}', 'App\Http\Controllers\UsersController@activate')->where('id', '[0-9]+')->where('code', '[0-9]+');
Route::get('/tproducts/create', 'App\Http\Controllers\TproductsController@create')->name('tproducts.create');

Route::group([
    'as' => 'mmail.',
    'prefix' => 'mmail',
], function () {
    Route::get('{url?}', 'App\Http\Controllers\MailusersController@edit')->where('url', '([A-z0-9-_\/.]+)?');
});

//public lk
Route::group([
    'as' => 'lk.',
    'prefix' => 'lk',
    'middleware' => ['auth']
], function () {
    Route::get('users/show', 'App\Http\Controllers\LK\UsersController@show')->name('users.show');
    Route::get('users/edit', 'App\Http\Controllers\LK\UsersController@edit')->name('users.edit');
    Route::post('users/update', 'App\Http\Controllers\LK\UsersController@update')->name('users.update');
    Route::post('baskets/ajax_add', 'App\Http\Controllers\LK\BasketsController@ajax_add')->name('baskets.ajax_add');
    Route::resource('baskets', App\Http\Controllers\LK\BasketsController::class);
    Route::resource('orders', App\Http\Controllers\LK\OrdersController::class, ['except' => ['index','create','edit']]);
});

Route::get('/admin', function () {
	if(!Auth::user()->hasPermissionTo('access-admin')) {
		return abort(404);
	}
    return view('layouts.admin');
})->middleware(['auth'])->name('dashboard');

//admin
Route::group([
    'as' => 'admin.',
    'prefix' => 'admin',
    'middleware' => ['auth']
], function () {
	Route::get('users/import', 'App\Http\Controllers\Admin\UsersController@import')->name('users.import');
	Route::get('orders/import', 'App\Http\Controllers\Admin\OrdersController@import')->name('orders.import');
	Route::get('timgs/del_files', 'App\Http\Controllers\Admin\TimgsController@del_files')->name('timgs.del_files');
	Route::get('imgs/del_imgs/{id}', 'App\Http\Controllers\Admin\ImgsController@del_imgs')->where('id', '[0-1]')->name('imgs.del_imgs');
	
    Route::resource('pages', PagesController::class, ['except' => ['show']]);
    Route::resource('products', ProductsController::class);
    Route::resource('roles', RolesController::class);
    Route::resource('users', App\Http\Controllers\Admin\UsersController::class);
    Route::resource('regions', RegionsController::class);
    Route::resource('cats', CatsController::class);
    Route::resource('props', PropsController::class);
	Route::resource('propvals', PropvalsController::class);
	Route::resource('tproducts', TproductsController::class, ['except' => ['index','create']]);
	Route::resource('tprops', TpropsController::class, ['except' => ['index','create','store','edit','update','show']]);

	Route::get('importlogs/clear_all', 'App\Http\Controllers\Admin\ImportlogsController@clear_all')->name('importlogs.clear_all');

	Route::resource('importlogs', ImportlogsController::class, ['except' => ['edit','update']]);
	Route::resource('imgs', ImgsController::class, ['except' => ['index']]);
	Route::resource('timgs', TimgsController::class, ['except' => ['index','create','edit','update']]);
	Route::resource('orders', OrdersController::class, ['except' => ['create','store']]);
	Route::resource('mailings', MailingsController::class);
	Route::resource('mailusers', MailusersController::class, ['except' => ['index','edit','update','show']]);
	Route::resource('settings', SettingsController::class, ['only' => ['index']]);

	Route::get('pages/show', 'App\Http\Controllers\Admin\PagesController@show')->name('pages.show');
	Route::post('products/save_img', 'App\Http\Controllers\Admin\ProductsController@save_image')->name('products.save_img');
	Route::get('users/activate/{id}/{code}', 'App\Http\Controllers\Admin\UsersController@activate')->where('id', '[0-9]+')->where('code', '[0-9]+')->name('users.activate');
	Route::get('tproducts/index/{id}', 'App\Http\Controllers\Admin\TproductsController@index')->where('id', '[0-9]+')->name('tproducts.index');
	Route::get('tproducts/create/{id}', 'App\Http\Controllers\Admin\TproductsController@create')->where('id', '[0-9]+')->name('tproducts.create');
	Route::get('timgs/index/{id}', 'App\Http\Controllers\Admin\TimgsController@index')->where('id', '[0-9]+')->name('timgs.index');
	Route::get('timgs/create/{id}', 'App\Http\Controllers\Admin\TimgsController@create')->where('id', '[0-9]+')->name('timgs.create');
	Route::get('timgs/edit/{id}', 'App\Http\Controllers\Admin\TimgsController@edit')->where('id', '[0-9]+')->name('timgs.edit');
	Route::get('timgs/update/{id}', 'App\Http\Controllers\Admin\TimgsController@update')->where('id', '[0-9]+')->name('timgs.update');
	Route::get('tprops/index/{id}', 'App\Http\Controllers\Admin\TpropsController@index')->where('id', '[0-9]+')->name('tprops.index');
	Route::get('tprops/create/{id}', 'App\Http\Controllers\Admin\TpropsController@create')->where('id', '[0-9]+')->name('tprops.create');
	Route::get('tprops/edit/{id}', 'App\Http\Controllers\Admin\TpropsController@edit')->where('id', '[0-9]+')->name('tprops.edit');
	Route::get('tprops/update/{id}', 'App\Http\Controllers\Admin\TpropsController@update')->where('id', '[0-9]+')->name('tprops.update');
	Route::get('tproducts/sync/{id}', 'App\Http\Controllers\Admin\TproductsController@sync')->where('id', '[0-9]+')->name('tproducts.sync');
	Route::get('mailings/build/{id}', 'App\Http\Controllers\Admin\MailingsController@build')->where('id', '[0-9]+')->name('mailings.build');
	Route::get('mailings/arrange/{id}', 'App\Http\Controllers\Admin\MailingsController@arrange')->where('id', '[0-9]+')->name('mailings.arrange');
	Route::get('mailusers/index/{id}', 'App\Http\Controllers\Admin\MailusersController@index')->where('id', '[0-9]+')->name('mailusers.index');
	Route::get('settings/edit/{id}/{is_active}', 'App\Http\Controllers\Admin\SettingsController@edit')->where('id', '[0-9]+')->where('is_active', '[0-1]+')->name('settings.edit');
    //Route::get('users', 'App\Http\Controllers\Admin\UsersController@index');
    
});


require __DIR__.'/auth.php';

/*
DB::listen(function($query) {
    echo "<pre>";
    var_dump($query->sql, $query->bindings, $query->time);
    echo "</pre>";
});
*/

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Cat;
use App\Models\Product;
use App\Models\Prop;
use App\Services\ProductService;
use Illuminate\Http\Request;
use Auth;

class ProductsController extends Controller
{
	protected $productService;

	function __construct(ProductService $productService)
    {
         $this->productService = $productService;
    }

    /**
	 * Shows Product's list info
	 * @param Request $request
	*/
    public function index(Request $request)
    {
    	$request->validate([
            'cat_id' => 'nullable|numeric',
            'in_stock' => 'nullable|numeric',
            'prop' => 'nullable|array',
            'prop.*' => 'nullable|array',
            'prop.*.*' => 'nullable|numeric',
        ]);

		//dd($request);

    	$cat = array();
    	$cond = array();
    	$cond[] = ['products.is_active', '=', 1];

    	$input = $request->query();
    	
    	if((isset($input['prop']) && !empty($input['prop'])) || (isset($input['searchw']) && !empty($input['searchw'])) || (isset($input['in_stock']) && ($input['in_stock'] == 1)) ) {
    		//$cond[] = ['products.parent_id', '!=', 0];
    	} else {
    		$cond[] = ['products.parent_id', '=', 0];
    	}

    	if (isset($input['searchw'])) {
    		$cond[] = ['products.name', 'like', '%'.$input['searchw'].'%'];
    	}
    	if (isset($input['cat_id']) && !empty($input['cat_id'])) {
    		$cat = Cat::select('id','name')
    			->findorfail($input['cat_id']);
    		$cond[] = ['products.cat_id', '=', $input['cat_id']];
    	}
    	if (isset($input['in_stock']) && ($input['in_stock'] == 1)) {
    		$cond[] = ['products.quantity', '>', 0];
    	}

		$products = Product::with(['cat', 'imgs' => function ($query) {
				$query->where('imgs.is_main', '=', 1)
					->orderBy('is_main');
				}
			])
			->withCount('children')
			->sortable();

		if (isset($input['prop']) && !empty($input['prop'])) {
			foreach($input['prop'] as $prop_key => $prop_val)
			{
				$products = $products->join('propvals as prop'.$prop_key, function ($join) use (&$prop_key) {
		            $join->on('products.id', '=', 'prop'.$prop_key.'.product_id')
						->where('prop'.$prop_key.'.prop_id', '=', $prop_key);
		        });

				$joinIn = array();

				foreach($prop_val as $kkey => $prop_value)
				{
					$joinIn[] = $prop_value;
				};
				$products = $products->whereIn('prop'.$prop_key.'.propvalue_id', $joinIn);
			};
		}

		$products = $products->where($cond)->paginate(18);

		//dump($products);

		$here = "products";

    	return view('products.index', compact('products','input','here','cat'));
    }

	/**
	 * Shows Product's detail info
	 * @param string $id
	*/
	public function show($id)
    {
	    $product = Product::with(['propvals', 
	    	'imgs' => function ($query) {
				$query->orderBy('is_main', 'desc');
			}])
			->withCount('children')
	    	->where([
	        	['products.is_active', '=', 1],
	        	['products.parent_id', '=', 0]
	        ])
	        ->findorfail($id);

		$addprods = array();

		if ($product->children->count() != 0) {
	        $addprods = $this->productService->formProductAddprods($id);
		}

		$props = Prop::all('id','name')
			->keyBy('id')
			->toArray();

		$here = "products";

        return view('products.show',compact('product', 'props', 'here', 'addprods'));
    }

}

resources/views/admin/products/create.blade.php
@extends('layouts.admin')

@section('content')
	<div class="admin-form">
		<h2><span>Новый товар</span></h2>

		<form method="post" action="{{ route('admin.products.store') }}">
	        @csrf
	        
	        <input type="hidden" name="parent_id" value="0">
	        
	        <div class="container">
	        	<div class="row row-cols-1 row-cols-lg-2">

					<div class="col">
				    	<div class="container">

				    		<div class="row mb-2">
								<div class="col-4"><label for="is_active">Активен</label></div>
								<div class="col-8">
				            		<input class="form-group" type="checkbox" name="is_active" @if (old('is_active')==1) checked @endif>
								</div>
				        	</div>

							<div class="row mb-2">
							    <div class="col-4"><label for="sort">Сортировка</label></div>
							    <div class="col-8">
							        <input type="text" name="sort" class="form-group w-100" value="{{ old('sort') }}" required />
							    </div>
							</div>

							<div class="row mb-2">
							    <div class="col-4"><label for="articul">Артикул</label></div>
							    <div class="col-8">
							        <input type="text" name="articul" class="form-group w-100" value="{{ old('articul') }}" required />
							    </div>
							</div>

							<div class="row mb-2">
							    <div class="col-4"><label for="name">Категория</label></div>
							    <div class="col-8">
							        <select name="cat_id" class="form-group">
								    	<option>-- не выбрано --</option>
									    @foreach($cats as $cat)
							                <option value="{{ $cat->id }}" @if (old('cat_id') == $cat->id) selected @endif>{{ $cat->name }}</option>
							            @endforeach
						            </select>
							    </div>
							</div>

					    </div>
				    </div>

		        	<div class="col">
		        		<div class="container">

							<div class="row mb-2">
							    <div class="col-4"><label for="weight">Вес (г)</label></div>
							    <div class="col-8">
							        <input type="text" name="weight" class="form-group w-100" value="{{ old('weight') }}" />
							    </div>
							</div>

		        			<div class="row mb-2">
							    <div class="col-4"><label for="quantity">Количество</label></div>
							    <div class="col-8">
							        <input type="text" name="quantity" class="form-group w-100" required value="{{ old('quantity') }}" />
							    </div>
							</div>

							<div class="row mb-2">
							    <div class="col-4"><label for="price">Цена</label></div>
							    <div class="col-8">
							        <input type="text" name="price" class="form-group w-100" value="{{ old('price') }}" />
							    </div>
							</div>

		        		</div>
				    </div>

			    </div>
		    </div>

			<div class="container">
		    	<div class="row">
		    		<div class="col mt-2">
		    			Название
		    		</div>
		    	</div>
		    	<div class="row">
		    		<div class="col">
		    			<input type="text" name="name" class="form-group w-100" value="{{ old('name') }}" />
		    		</div>
		    	</div>
		    	<div class="row mt-2">
		    		<div class="col">
		    			SKU
		    		</div>
		    	</div>
		    	<div class="row">
		    		<div class="col">
		    			<input type="text" name="sku" class="form-group w-100" value="{{ old('sku') }}" />
		    		</div>
		    	</div>
		    	<div class="row mt-2">
		    		<div class="col">
		    			Комментарий
		    		</div>
		    	</div>
		    	<div class="row">
		    		<div class="col">
		    			<textarea name="comment" class="form-control" rows="2">{{ old('comment') }}</textarea>
		    		</div>
		    	</div>
		    </div>

			<div class="container buttons_block">
	        	<div class="row text-center justify-content-center">
	        		<div class="buttons_block_sub" style="width: 400px;">

	        			<div class="container">
	        				<div class="row">
								<div class="col">
						            <button class="" type="submit">Сохранить</button>
						        </div>
						        <div class="col"><a href="{{ route('admin.products.index') }}">Отмена</a></div>
						    </div>
						</div>

			    	</div>
				</div>
	        </div>
	        
	    </form>
    </div>
@endsection

resources/views/admin/products/edit.blade.php
@extends('layouts.admin')

@section('content')
	<div class="admin-form">
		<h2><span>Редактирование товара "{{ $product->articul }}"</span></h2>

		<form method="post" action="{{ route('admin.products.update', $product->id) }}">
	        @method('PATCH')
		    @csrf
	        
	        <div class="container">
	        	<div class="row row-cols-1 row-cols-lg-2">

					<div class="col">
				    	<div class="container">

				    		<div class="row mb-2">
								<div class="col-4"><label for="is_active">Активен</label></div>
								<div class="col-8">
				            		<input class="form-group" type="checkbox" name="is_active" @if ($product->is_active == 1) checked @endif>
								</div>
				        	</div>

							<div class="row mb-2">
							    <div class="col-4"><label for="sort">Сортировка</label></div>
							    <div class="col-8">
							        <input type="text" name="sort" class="form-group w-100" value="{{ old('sort') ?? $product->sort ?? '' }}" required />
							    </div>
							</div>

							<div class="row mb-2">
							    <div class="col-4"><label for="articul">Артикул</label></div>
							    <div class="col-8">
							        <input type="text" name="articul" class="form-group w-100" value="{{ old('articul') ?? $product->articul ?? '' }}" required />
							    </div>
							</div>

							<div class="row mb-2">
							    <div class="col-4"><label for="name">Категория</label></div>
							    <div class="col-8">
							        <select name="cat_id" class="form-group">
								    	<option>-- не выбрано --</option>
									    @foreach($cats as $cat)
							                <option value="{{ $cat->id }}" @if ($product->cat_id == $cat->id || old('cat_id') == $cat->id) selected @endif>{{ $cat->name }}</option>
							            @endforeach
						            </select>
							    </div>
							</div>

					    </div>
				    </div>

		        	<div class="col">
		        		<div class="container">

							<div class="row mb-2">
							    <div class="col-4"><label for="weight">Вес (г)</label></div>
							    <div class="col-8">
							        <input type="text" name="weight" class="form-group w-100" value="{{ old('weight') ?? $product->weight ?? '' }}" />
							    </div>
							</div>

		        			<div class="row mb-2">
							    <div class="col-4"><label for="quantity">Количество</label></div>
							    <div class="col-8">
							        <input type="text" name="quantity" class="form-group w-100" value="{{ old('quantity') ?? $product->quantity ?? '' }}" />
							    </div>
							</div>

							<div class="row mb-2">
							    <div class="col-4"><label for="price">Цена</label></div>
							    <div class="col-8">
							        <input type="text" name="price" class="form-group w-100" value="{{ old('price') ?? $product->price ?? '' }}" />
							    </div>
							</div>

		        		</div>
				    </div>

			    </div>
		    </div>

			<div class="container">
		    	<div class="row">
		    		<div class="col mt-2">
		    			Название
		    		</div>
		    	</div>
		    	<div class="row">
		    		<div class="col">
		    			<input type="text" name="name" class="form-group w-100" value="{{ old('name') ?? $product->name ?? '' }}" />
		    		</div>
		    	</div>
		    	<div class="row mt-2">
		    		<div class="col">
		    			SKU
		    		</div>
		    	</div>
		    	<div class="row">
		    		<div class="col">
		    			<input type="text" name="sku" class="form-group w-100" value="{{ old('sku') ?? $product->sku ?? '' }}" />
		    		</div>
		    	</div>
		    	<div class="row mt-2">
		    		<div class="col">
		    			Комментарий
		    		</div>
		    	</div>
		    	<div class="row">
		    		<div class="col">
		    			<textarea name="comment" class="form-control" rows="2">{{ old('comment') ?? $product->comment ?? '' }}</textarea>
		    		</div>
		    	</div>
		    </div>

			<div class="container buttons_block">
	        	<div class="row text-center justify-content-center">
	        		<div class="buttons_block_sub" style="width: 400px;">

	        			<div class="container">
	        				<div class="row">
								<div class="col">
						            <button class="" type="submit">Сохранить</button>
						        </div>
						        <div class="col"><a href="{{ route('admin.products.index') }}">Отмена</a></div>
						    </div>
						</div>

			    	</div>
				</div>
	        </div>
	        
	    </form>
    </div>
@endsection

resources/views/admin/products/index.blade.php
@extends('layouts.admin')

@section('content')

<h1>Все товары</h1>

<div class="container">

	<h2>Товары</h2>

	<p>&nbsp;</p>

	<div class="row">
		<div class="col text-end">
			<form method="get" action="{{ route('admin.products.index') }}">
				<div class="">
					 <input type="text" placeholder="Поиск..." name="searchw" class="form-group w-100" value="{{ $input['searchw'] ?? '' }}" />
				</div>
				<div class="mb-2 text-muted small">поиск по названию, артикулу, SKU</div>
				<div class="mb-2">
					<button class="" type="submit">Применить</button>
				</div>
		    </form>
    	</div>
	</div>
	
	<div class="row">
		<div class="col">
			{!! $products->appends(Request::except('page'))->render() !!}
		</div>
		<div class="col text-end">
			Всего: {{ $products->total() }}
		</div>
	</div>

	<div class="row">
		<div class="col table-responsive">
		    <table class="table table-striped table-hover table-sm table-bordered">
		        <thead>
		        <tr class="table-secondary text-center">
		            <th>#</th>
					<th rowspan="2">@sortablelink('sort', 'Сорт')</th>
					<th rowspan="2"></th>
		            <th>@sortablelink('name', 'Название')</th>
		            <th rowspan="2">@sortablelink('articul', 'Артикул')</th>
					<th rowspan="2">@sortablelink('weight', 'Вес')</th>
					<th>@sortablelink('price', 'Цена')</th>
		            <th rowspan="2" title="Активность на сайте">ОП</th>
		            <th rowspan="2"></th>
		        </tr>
				<tr class="table-secondary text-center">
		            <th>(ID)</th>
		            <th>(Категория)</th>
					<th>@sortablelink('quantity', '(Кол-во)')</th>
		        </tr>
		        </thead>
		        <tbody>
		            @php
		                $i = 0;
		            @endphp
		            @foreach ($products as $product)
		                @php
		                    $i++;
		                @endphp
		                <tr>
		                    <td class="text-center">{{ $i }} ({{ $product->id }})</td>
		                    <td class="text-center">{{ $product->sort }}</td>
		                    <td style="max-width: 100px;">
		                    	<div style="width: 100px;">
		                    	@if($product->imgs->count() > 0)
		                    		<a data-fancybox="gallery" href="{{ Storage::disk('public')->url($product->imgs[0]->url."/".$product->imgs[0]->file) }}"><img src="{{ Helper::image_resizer($product->imgs[0]->url."/".$product->imgs[0]->file, 100) }}" class="w-100" /></a>
		                    	@else
		                    		<img src="{{ Storage::disk('public')->url('catalog/noimg.jpg') }}" alt="" class="w-100" />
			                    @endif
			                    </div>
			                </td>
		                    <td>
		                    	@can('product-show')<a href="{{ route('admin.products.show', $product->id) }}">@endcan
		                    	{{ $product->name }}
		                    	@can('product-show')</a>@endcan
		                    	@if($product->children->count() > 0) (+{{ $product->children->count() }}) @endif
		                    	({{ $product->cat->name ?? '' }})
			                </td>
		                    <td class="text-center">{{ $product->articul }}</td>
		                    <td class="text-center">{{ $product->weight }}</td>
		                    <td class="text-center">{{ $product->price }} ({{ $product->quantity }})
		                    </td>
		                    <td class="text-center">
		                        @if ($product->is_active == 1)
		                            <span class="text-success">Да</span>
		                        @else
		                            <span class="text-danger">Нет</span>
		                        @endif
		                    </td>
		                    <td class="text-center actions">
		                    	@can('product-edit')
		                    	<a class="act_butt" title="Редактировать" href="{{ route('admin.products.edit', $product->id) }}">ред.</a>
		                    	@endcan

		                    	@can('product-delete')
		                    	@if($product->children->count() == 0)
		                        <form action="{{ route('admin.products.destroy', ['product' => $product->id]) }}"
			                          method="post" onsubmit="return confirm('Вы действительно хотите удалить {{ $product->name }} ?')">
			                          @csrf
			                          @method('DELETE')
			                          <button type="submit" title="Удалить" class="act_butt m-0 border-0 bg-transparent text-primary"><u>X</u></button>
			                    </form>
			                    @endif
			                    @endcan
		                    </td>
		                </tr>
		            @endforeach
		        </tbody>
		    </table>

		</div>
	</div>

	<div class="row">
		<div class="col">
			{!! $products->appends(Request::except('page'))->render() !!}
		</div>
		<div class="col text-end">
			Всего: {{ $products->total() }}
		</div>
	</div>

</div>

@endsection