routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\ProductsController;
use App\Http\Controllers\Admin\RolesController;
use App\Http\Controllers\Admin\RegionsController;
use App\Http\Controllers\Admin\PagesController;
use App\Http\Controllers\Admin\CatsController;
use App\Http\Controllers\Admin\PropsController;
use App\Http\Controllers\Admin\PropvalsController;
use App\Http\Controllers\Admin\TproductsController;
use App\Http\Controllers\Admin\ImportlogsController;
use App\Http\Controllers\Admin\ImgsController;
use App\Http\Controllers\Admin\TimgsController;
use App\Http\Controllers\Admin\TpropsController;
use App\Http\Controllers\Admin\OrdersController;
use App\Http\Controllers\Admin\MailingsController;
use App\Http\Controllers\Admin\MailusersController;
use App\Http\Controllers\Admin\SettingsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('layouts.app');
});*/

Route::get('/', 'App\Http\Controllers\PagesController@index');

Route::get('/products', 'App\Http\Controllers\ProductsController@index')->name('products');
Route::get('/products/{id}', 'App\Http\Controllers\ProductsController@show')->where('id', '[0-9]+')->name('products.show');
Route::get('/pages/{url}', 'App\Http\Controllers\PagesController@view')->where('url', '[A-Za-z0-9]+');
Route::get('/mailusers/index', 'App\Http\Controllers\MailusersController@index');
Route::get('/users/activate/{id}/{code}', 'App\Http\Controllers\UsersController@activate')->where('id', '[0-9]+')->where('code', '[0-9]+');
Route::get('/tproducts/create', 'App\Http\Controllers\TproductsController@create')->name('tproducts.create');

Route::group([
    'as' => 'mmail.',
    'prefix' => 'mmail',
], function () {
    Route::get('{url?}', 'App\Http\Controllers\MailusersController@edit')->where('url', '([A-z0-9-_\/.]+)?');
});

//public lk
Route::group([
    'as' => 'lk.',
    'prefix' => 'lk',
    'middleware' => ['auth']
], function () {
    Route::get('users/show', 'App\Http\Controllers\LK\UsersController@show')->name('users.show');
    Route::get('users/edit', 'App\Http\Controllers\LK\UsersController@edit')->name('users.edit');
    Route::post('users/update', 'App\Http\Controllers\LK\UsersController@update')->name('users.update');
    Route::post('baskets/ajax_add', 'App\Http\Controllers\LK\BasketsController@ajax_add')->name('baskets.ajax_add');
    Route::resource('baskets', App\Http\Controllers\LK\BasketsController::class);
    Route::resource('orders', App\Http\Controllers\LK\OrdersController::class, ['except' => ['index','create','edit']]);
});

Route::get('/admin', function () {
	if(!Auth::user()->hasPermissionTo('access-admin')) {
		return abort(404);
	}
    return view('layouts.admin');
})->middleware(['auth'])->name('dashboard');

//admin
Route::group([
    'as' => 'admin.',
    'prefix' => 'admin',
    'middleware' => ['auth']
], function () {
	Route::get('users/import', 'App\Http\Controllers\Admin\UsersController@import')->name('users.import');
	Route::get('orders/import', 'App\Http\Controllers\Admin\OrdersController@import')->name('orders.import');
	Route::get('timgs/del_files', 'App\Http\Controllers\Admin\TimgsController@del_files')->name('timgs.del_files');
	Route::get('imgs/del_imgs/{id}', 'App\Http\Controllers\Admin\ImgsController@del_imgs')->where('id', '[0-1]')->name('imgs.del_imgs');
	
    Route::resource('pages', PagesController::class, ['except' => ['show']]);
    Route::resource('products', ProductsController::class);
    Route::resource('roles', RolesController::class);
    Route::resource('users', App\Http\Controllers\Admin\UsersController::class);
    Route::resource('regions', RegionsController::class);
    Route::resource('cats', CatsController::class);
    Route::resource('props', PropsController::class);
	Route::resource('propvals', PropvalsController::class);
	Route::resource('tproducts', TproductsController::class, ['except' => ['index','create']]);
	Route::resource('tprops', TpropsController::class, ['except' => ['index','create','store','edit','update','show']]);

	Route::get('importlogs/clear_all', 'App\Http\Controllers\Admin\ImportlogsController@clear_all')->name('importlogs.clear_all');

	Route::resource('importlogs', ImportlogsController::class, ['except' => ['edit','update']]);
	Route::resource('imgs', ImgsController::class, ['except' => ['index']]);
	Route::resource('timgs', TimgsController::class, ['except' => ['index','create','edit','update']]);
	Route::resource('orders', OrdersController::class, ['except' => ['create','store']]);
	Route::resource('mailings', MailingsController::class);
	Route::resource('mailusers', MailusersController::class, ['except' => ['index','edit','update','show']]);
	Route::resource('settings', SettingsController::class, ['only' => ['index']]);

	Route::get('pages/show', 'App\Http\Controllers\Admin\PagesController@show')->name('pages.show');
	Route::post('products/save_img', 'App\Http\Controllers\Admin\ProductsController@save_image')->name('products.save_img');
	Route::get('users/activate/{id}/{code}', 'App\Http\Controllers\Admin\UsersController@activate')->where('id', '[0-9]+')->where('code', '[0-9]+')->name('users.activate');
	Route::get('tproducts/index/{id}', 'App\Http\Controllers\Admin\TproductsController@index')->where('id', '[0-9]+')->name('tproducts.index');
	Route::get('tproducts/create/{id}', 'App\Http\Controllers\Admin\TproductsController@create')->where('id', '[0-9]+')->name('tproducts.create');
	Route::get('timgs/index/{id}', 'App\Http\Controllers\Admin\TimgsController@index')->where('id', '[0-9]+')->name('timgs.index');
	Route::get('timgs/create/{id}', 'App\Http\Controllers\Admin\TimgsController@create')->where('id', '[0-9]+')->name('timgs.create');
	Route::get('timgs/edit/{id}', 'App\Http\Controllers\Admin\TimgsController@edit')->where('id', '[0-9]+')->name('timgs.edit');
	Route::get('timgs/update/{id}', 'App\Http\Controllers\Admin\TimgsController@update')->where('id', '[0-9]+')->name('timgs.update');
	Route::get('tprops/index/{id}', 'App\Http\Controllers\Admin\TpropsController@index')->where('id', '[0-9]+')->name('tprops.index');
	Route::get('tprops/create/{id}', 'App\Http\Controllers\Admin\TpropsController@create')->where('id', '[0-9]+')->name('tprops.create');
	Route::get('tprops/edit/{id}', 'App\Http\Controllers\Admin\TpropsController@edit')->where('id', '[0-9]+')->name('tprops.edit');
	Route::get('tprops/update/{id}', 'App\Http\Controllers\Admin\TpropsController@update')->where('id', '[0-9]+')->name('tprops.update');
	Route::get('tproducts/sync/{id}', 'App\Http\Controllers\Admin\TproductsController@sync')->where('id', '[0-9]+')->name('tproducts.sync');
	Route::get('mailings/build/{id}', 'App\Http\Controllers\Admin\MailingsController@build')->where('id', '[0-9]+')->name('mailings.build');
	Route::get('mailings/arrange/{id}', 'App\Http\Controllers\Admin\MailingsController@arrange')->where('id', '[0-9]+')->name('mailings.arrange');
	Route::get('mailusers/index/{id}', 'App\Http\Controllers\Admin\MailusersController@index')->where('id', '[0-9]+')->name('mailusers.index');
	Route::get('settings/edit/{id}/{is_active}', 'App\Http\Controllers\Admin\SettingsController@edit')->where('id', '[0-9]+')->where('is_active', '[0-1]+')->name('settings.edit');
    //Route::get('users', 'App\Http\Controllers\Admin\UsersController@index');
    
});


require __DIR__.'/auth.php';

/*
DB::listen(function($query) {
    echo "<pre>";
    var_dump($query->sql, $query->bindings, $query->time);
    echo "</pre>";
});
*/

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Cat;
use App\Models\Product;
use App\Models\Prop;
use App\Services\ProductService;
use Illuminate\Http\Request;
use Auth;

class ProductsController extends Controller
{
	protected $productService;

	function __construct(ProductService $productService)
    {
         $this->productService = $productService;
    }

    /**
	 * Shows Product's list info
	 * @param Request $request
	*/
    public function index(Request $request)
    {
    	$request->validate([
            'cat_id' => 'nullable|numeric',
            'in_stock' => 'nullable|numeric',
            'prop' => 'nullable|array',
            'prop.*' => 'nullable|array',
            'prop.*.*' => 'nullable|numeric',
        ]);

		//dd($request);

    	$cat = array();
    	$cond = array();
    	$cond[] = ['products.is_active', '=', 1];

    	$input = $request->query();
    	
    	if((isset($input['prop']) && !empty($input['prop'])) || (isset($input['searchw']) && !empty($input['searchw'])) || (isset($input['in_stock']) && ($input['in_stock'] == 1)) ) {
    		//$cond[] = ['products.parent_id', '!=', 0];
    	} else {
    		$cond[] = ['products.parent_id', '=', 0];
    	}

    	if (isset($input['searchw'])) {
    		$cond[] = ['products.name', 'like', '%'.$input['searchw'].'%'];
    	}
    	if (isset($input['cat_id']) && !empty($input['cat_id'])) {
    		$cat = Cat::select('id','name')
    			->findorfail($input['cat_id']);
    		$cond[] = ['products.cat_id', '=', $input['cat_id']];
    	}
    	if (isset($input['in_stock']) && ($input['in_stock'] == 1)) {
    		$cond[] = ['products.quantity', '>', 0];
    	}

		$products = Product::with(['cat', 'imgs' => function ($query) {
				$query->where('imgs.is_main', '=', 1)
					->orderBy('is_main');
				}
			])
			->withCount('children')
			->sortable();

		if (isset($input['prop']) && !empty($input['prop'])) {
			foreach($input['prop'] as $prop_key => $prop_val)
			{
				$products = $products->join('propvals as prop'.$prop_key, function ($join) use (&$prop_key) {
		            $join->on('products.id', '=', 'prop'.$prop_key.'.product_id')
						->where('prop'.$prop_key.'.prop_id', '=', $prop_key);
		        });

				$joinIn = array();

				foreach($prop_val as $kkey => $prop_value)
				{
					$joinIn[] = $prop_value;
				};
				$products = $products->whereIn('prop'.$prop_key.'.propvalue_id', $joinIn);
			};
		}

		$products = $products->where($cond)->paginate(18);

		//dump($products);

		$here = "products";

    	return view('products.index', compact('products','input','here','cat'));
    }

	/**
	 * Shows Product's detail info
	 * @param string $id
	*/
	public function show($id)
    {
	    $product = Product::with(['propvals', 
	    	'imgs' => function ($query) {
				$query->orderBy('is_main', 'desc');
			}])
			->withCount('children')
	    	->where([
	        	['products.is_active', '=', 1],
	        	['products.parent_id', '=', 0]
	        ])
	        ->findorfail($id);

		$addprods = array();

		if ($product->children->count() != 0) {
	        $addprods = $this->productService->formProductAddprods($id);
		}

		$props = Prop::all('id','name')
			->keyBy('id')
			->toArray();

		$here = "products";

        return view('products.show',compact('product', 'props', 'here', 'addprods'));
    }

}

resources/views/products/index.blade.php
@extends('layouts.app')

@if(isset($cat) && !empty($cat))
	@section('title', 'Товары категории '.$cat->name ?? '')
	@section('description', 'Товары категории '.$cat->name ?? '')
@else
	@section('title', 'Каталог продукции')
	@section('description', 'Каталог продукции')
@endif

@section('content')


@if(isset($cat) && !empty($cat))
	<h1>{{ $cat->name ?? '' }}</h1>
@else
	<h1>Все товары</h1>
@endif

	<div class="sort_links text-end"><span class="sorting_text">Сортировать по:</span> @sortablelink('price', 'Цене') <span class="divider">|</span> @sortablelink('quantity', 'Наличию') <span class="divider">|</span> @sortablelink('name', 'Названию') <span class="divider">|</span> @sortablelink('weight', 'Весу')</div>

	<div class="prod_catalog row row-cols-1 row-cols-sm-2 row-cols-xl-3 align-content-stretch">
	@foreach ($products as $product)
		<div class="prod_item d-flex flex-column">
			<div class="prod_img text-center mb-auto">
				<a class="d-block align-items-center" href="@if(isset($product->parent)) {{ route('products.show', $product->parent_id) }} @else {{ route('products.show', $product->id) }} @endif" style="background-image: url('@if($product->imgs->count() > 0){{ Helper::image_resizer($product->imgs[0]->url."/".$product->imgs[0]->file, 200) }}@else{{ Storage::disk('public')->url('catalog/noimg.jpg') }}@endif');">&nbsp;
				</a>
			</div>

			<div class="prod_props">
				<div class="prod_name text-center">{{ $product->name }}</div>
				<div class="row">
					<div class="col text-secondary text-end">категория: </div>
					<div class="col">{{ $product->cat->name ?? '' }}</div>
				</div>
				@if(!empty($product->articul))
					<div class="row">
						<div class="col text-secondary text-end">артикул: </div>
						<div class="col">{{ $product->articul }}</div>
					</div>
				@endif
				@if($product->weight != '0.000')
					<div class="row">
						<div class="col text-secondary text-end">сред. вес: </div>
						<div class="col">{{ $product->weight }} г</div>
					</div>
				@endif
				{{--
				<div class="row">
					<div class="col text-secondary text-end">sku: </div>
					<div class="col">{{ $product->sku }}</div>
				</div>
				<div class="row">
					<div class="col text-secondary text-end">SKU Категории: </div>
					<div class="col">{{ $product->cat->sku ?? '' }}</div>
				</div>
				--}}
			</div>

			<div class="prod_price_box mt-auto">
				@if($product->children_count == 0)
					<div class="row prod_price">
						@include('layouts.elements.price',[
							'prod_quantity' => $product->quantity,
							'prod_price' => $product->price,
						])
					</div>
					<div class="row prod_basket">
						@include('layouts.elements.add2basket',['product_id' => $product->id])
					</div>
				@endif
				<div class="row prod_read_more">
					<div class="col text-center">
						@if(isset($product->parent))
							<a href="{{ route('products.show', $product->parent->id) }}">подробнее</a>
						@else
							<a href="{{ route('products.show', $product->id) }}">подробнее</a>
						@endif
					</div>
				</div>
			</div>
		</div>
	@endforeach
	</div>

	<p>&nbsp;</p>

	<div class="row">
		{!! $products->appends(Request::except('page'))->render() !!}
	</div>

@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('title', 'Каталог.'.$product->name)
@section('description', 'Каталог.'.$product->name)

@section('content')

<h1>{{ $product->name }}</h1>


	<div class="row row-cols-1 row-cols-lg-2">
	    <div class="col">
	    	<div class="row">
		    	@if($product->imgs->count() > 0)
					<a data-fancybox="gallery" href="{{ Storage::disk('public')->url($product->imgs[0]->url."/".$product->imgs[0]->file) }}"><img src="{{ Helper::image_resizer($product->imgs[0]->url."/".$product->imgs[0]->file, 400) }}" class="w-100" /></a>
				@else
					<div class="d-flex justify-content-center align-items-center"><img src="{{ Storage::disk('public')->url('catalog/noimg.jpg') }}" alt="" class="w-100" /></div>
				@endif
			</div>
			@if($product->imgs->count() > 1)
			<div class="row detail_small_imgs">
				@foreach($product->imgs as $img)
					<div class="col">
						<a data-fancybox="gallery" class="d-block" href="{{ Storage::disk('public')->url($img->url."/".$img->file) }}" style="background-image: url('{{ Storage::disk('public')->url($img->url."/".$img->file) }}');"></a>
					</div>
				@endforeach
			</div>
			@endif
	    </div>
	    <div class="col">

			@if(!empty($product->articul))
			<div class="row">
				<div class="col text-secondary text-end">Артикул:</div>
				<div class="col">{{ $product->articul }}</div>
			</div>
			@endif

			@if($product->weight != '0.000')
			<div class="row">
				<div class="col text-secondary text-end">Средний вес: </div>
				<div class="col">{{ $product->weight }} г</div>
			</div>
			@endif
			@if(empty($addprods))
				<p>&nbsp;</p>
				@include('layouts.elements.price',[
					'prod_quantity' => $product->quantity,
					'prod_price' => $product->price,
				])
				<p>&nbsp;</p>
				@include('layouts.elements.add2basket',['product_id' => $product->id])
				<p>&nbsp;</p>
			@endif
			
			@if($product->propvals->count() != 0)
				@foreach ($product->propvals as $propval)
					@if(!empty($propval->value))
					<div class="row">
						<div class="col text-secondary text-end">{{ $propval->prop->name }}:</div>
						<div class="col"> {{ $propval->value }}</div>
					</div>
					@endif
				@endforeach
			@endif
			
			@php
				//dump($addprods);
				//dd($props);
			@endphp
			
			@if(isset($addprods['add_props']))
				@foreach ($addprods['add_props'] as $prop_key => $prop_val)
					@if(!empty($prop_val))
					<div class="row">
						<div class="col text-secondary text-end">{{ $props[$prop_key]['name'] ?? '' }}:</div>
						<div class="col">{{ $prop_val }}</div>
					</div>
					@endif
				@endforeach
			@endif
		</div>
	</div>

	@if(isset($addprods) && !empty($addprods))

		@php
			//dump($addprods);
			$first_prop = array_key_first($addprods['props']);
			$last_prop = array_key_last($addprods['props'])
		@endphp

		<p>&nbsp;</p>
		<h2>Характеристики</h2>
		<p>&nbsp;</p>

		@if(!Auth::check())
			<div class="col text-center text-muted small">для отображения характеристик, цен и заказа необходимо <a href="{{ route('login') }}">авторизоваться</a></div>
		@else

		<table class="table table-striped table-hover table-sm table-bordered addit_products">
		<thead class="sticky_head">
			@if(count($addprods['props']) == 2)
				<tr>
					<th></th>
					<th colspan="{{ count($addprods['props'][$first_prop]) }}" class="text-center">{{ $props[$first_prop]['name'] }}</th>
				</tr>
				<tr>
					<th class="text-center">{{ $props[$last_prop]['name'] }}</th>
				@foreach ($addprods['props'][$first_prop] as $fkey => $fval)
					<th class="text-center">{{ $fkey }}</th>
				@endforeach
			@elseif(count($addprods['props']) == 1)
				<tr>
				<th></th>
				<th class="text-center">Артикул</th>
				<th class="text-center">{{ $props[$first_prop]['name'] }}</th>
				<th class="text-center">Сред. вес</th>
				<th class="text-center">Цена</th>
				<th class="text-center"></th>
				</tr>
			@else
				<tr>
				<th></th>
				<th class="text-center">Артикул</th>
				<th class="text-center">Характеристики</th>
				<th class="text-center">Сред. вес</th>
				<th class="text-center">Цена</th>
				<th class="text-center"></th>
				</tr>
			@endif
		</thead>
		<tbody>
			@if(count($addprods['props']) == 2)
				@php
					$i = 0;
				@endphp
				@foreach ($addprods['props'][$last_prop] as $lkey => $lval)
				<tr>
					<td class="text-center">{{ $lkey }}</td>
					@foreach ($addprods['props'][$first_prop] as $fkey => $fval)
						<td>
							<div class="add2basket_tabled"></div>
							<div class="row">
							@foreach($fval as $fprod_id=>$fprod_details)
								@if(isset($lval[$fprod_id]))
									<div class="col">
										<div class="mb-2 text-center">{{ $lval[$fprod_id]['articul'] }}</div>
										<div class="mb-2 text-center">
											@if($lval[$fprod_id]['weight'] != '0.000')
												ср. вес: {{ $lval[$fprod_id]['weight'] }} г
											@endif
										</div>
										<div class="mb-4 mt-2">
											<span title="{{ $lval[$fprod_id]['articul'] }}">
												@include('layouts.elements.price',[
													'prod_quantity' => $lval[$fprod_id]['quantity'],
													'prod_price' => $lval[$fprod_id]['price'],
												])
											</span>
										</div>
										<div class="mb-2">
											@include('layouts.elements.add2basket',['product_id' => $fprod_id])
										</div>
									</div>
								@endif
							@endforeach
							</div>
						</td>
					@endforeach
				</tr>
				@endforeach
			@elseif(count($addprods['props']) == 1)
				@foreach ($addprods['props'][$first_prop] as $fkey => $fval)
					<tr>
						<td class="text-center" style="max-width: 100px;">
							@if(isset($fval[array_key_first($fval)]['img']) && !empty($fval[array_key_first($fval)]['img']))
								<a class="zoom" href="{{ Storage::disk('public')->url($fval[array_key_first($fval)]['img']) }}"><img src="{{ Helper::image_resizer($fval[array_key_first($fval)]['img'], 400) }}" class="w-100" /></a>
							@else
								<div class="d-flex justify-content-center align-items-center"><img src="{{ Storage::disk('public')->url('catalog/noimg.jpg') }}" alt="" class="w-100" /></div>
							@endif
						</td>
						<td class="text-center">{{ $fval[array_key_first($fval)]['articul'] }}</td>
						<td class="text-center">{{ $fkey }}</td>
						<td class="text-center">
							@if($fval[array_key_first($fval)]['weight'] != '0.000')
								{{ $fval[array_key_first($fval)]['weight'] }} г
							@endif
						</td>
						<td class="text-center">
							@include('layouts.elements.price',[
								'prod_quantity' => $fval[array_key_first($fval)]['quantity'],
								'prod_price' => $fval[array_key_first($fval)]['price'],
							])
						</td>
						<td class="text-center">@include('layouts.elements.add2basket',['product_id' => array_key_first($fval)])</td>
					</tr>
				@endforeach
			@else
				@foreach ($addprods['prods'] as $prod_key => $prod_val)
				<tr>
					<td class="text-center" style="max-width: 100px;">
						@if(isset($prod_val['product']['img']) && !empty($prod_val['product']['img']))
							<a class="zoom" href="{{ Storage::disk('public')->url($prod_val['product']['img']) }}"><img src="{{ Helper::image_resizer($prod_val['product']['img'], 400) }}" class="w-100" /></a>
						@else
							<div class="d-flex justify-content-center align-items-center"><img src="{{ Storage::disk('public')->url('catalog/noimg.jpg') }}" alt="" class="w-100" /></div>
						@endif
					</td>
					<td>{{ $prod_val['product']['articul'] }}</td>
					<td class="text-center">
						@foreach($prod_val['props'] as $prod_val_key => $prod_val_val)
							@if(!isset($addprods['add_props'][$prod_val_key]))
								{{ $props[$prod_val_key]['name'] }}: {{ $prod_val_val }}<br />
							@endif
						@endforeach
					</td>
					<td>
						@if($prod_val['product']['weight'] != '0.000')
							{{ $prod_val['product']['weight'] }} г
						@endif
					</td>
					<td class="text-center">
						@include('layouts.elements.price',[
							'prod_quantity' => $prod_val['product']['quantity'],
							'prod_price' => $prod_val['product']['price'],
						])
					</td>
					<td class="text-center">@include('layouts.elements.add2basket',['product_id' => $prod_key])</td>
				</tr>
				@endforeach
			@endif
		</tbody>
		</table>
		@endif

	@endif

@endsection